### ISSUE TITLE
COuntdown timer only on presentation slides of xaringan?

### ISSUE THREAD

**Issue by sje30** [gadenbuie/countdown#15]
Can the countdown timer be added just on the presenter's slides, rather than on the main slides in xaringan?  I'd like to see the timer as a presenter, but don't wat the audience to see it.

(remark.js does have the timer, but it is not a countdown...)

Thank you for a great package.

**Comment by gadenbuie** [comment]
Thanks for the feature request! I don't think it's possible to differentiate between the presenter's slides and the second cloned slides.

The best alternative I can think of at the moment would be to put the countdown timer in the presenters notes, i.e.

```
... slide content ...

???

`r countdown::countdown(2)`
```

but in my testing you have to load the slides, then enable presenter mode (press P) and then reload the slides for the timer start click to work. This might be fixable in future versions of `countdown`.

**Comment by sje30** [comment]
Thanks for the comments!

**Comment by gadenbuie** [comment]
I came back to look at this and can say now for certain that timers in the presenter notes are not going to work because of limitations with how remarkjs adds the presenter notes content into the page. Basically the presenter notes content is written into the DOM just before showing it and then removed when you move to the next slide so the timers are destroyed if you move to a new slide and they can't be initiated on page load.

**Comment by sje30** [comment]
Thank you for looking into it again; appreciated.
