### ISSUE TITLE
Custom sound set by `play_sound` not playing.

### ISSUE THREAD

**Issue by coatless** [gadenbuie/countdown#44]
Repo: 

```r
# Retrieve a copy of the embedded sound 
download.file(
  "https://github.com/gadenbuie/countdown/raw/main/lib/smb_stage_clear.mp3", 
  "test-beep.mp3")

# Test sound
countdown::countdown(minutes = 0, seconds = 1, play_sound = "test-beep.mp3")
```

I think the issue is the JS library is assuming the sound is placed relative to the `js` file instead of being in the working directory.

Error when countdown hits zero is: 

```default
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```

**Comment by gadenbuie** [comment]
This is an interesting case. What's important here is two things:

1. `countdown::countdown()` is called interactively and therefore previewed via `htmltools::browsable()`.
2. There's a custom sound being used.

This differs from the primary use of `countdown::countdown()` in a webpage or Shiny app, where there's a web server hosting the webpage and the supporting files. So `countdown()` expects the `play_sound` argument contains a path to the served file once `countdown()` is deployed.

In this case, though, `htmltools::browsable()` renders the timer into a temporary html file and then opens that temp file. There's a chance that using `play_sound = "file:///Users/garrick/path/to/file/test-beep.mp3"` would work locally, but that's up to the browser and what restrictions it places on accessing local files (if it works it'd be a pleasant surprise).

If we were to make a change to `countdown()` it would have to be specific to how the temporary html file is rendered by `htmltools::browsable()`. Or _maybe_ we could embed the file using base64 encoding, but that would bloat the page size because each usage is independent.

I think our best option would be to better document this behavior as a limitation.
